import os
from typing import List

class ChecklistGenerator:
    """
    Tool suite for generating compliance and verification documents.
    """

    def generate_human_verification_checklist(self, checklist_items: List[str], output_path: str = "outputs/compliance_report.md") -> str:
        """
        Creates a pre-submission compliance checklist document in Markdown format to facilitate human review.
        To avoid swamping the LLM's output context with large data tables or documents, this tool writes the 
        content directly to the local file system and only returns the file path.

        Args:
            checklist_items (List[str]): A list of string descriptions representing the required criteria to be checked.
            output_path (str, optional): The destination file path for the generated checklist. Be sure to document 
                                         default values correctly. Defaults to 'outputs/compliance_report.md'.

        Returns:
            str: A short string representing the file path to the successfully generated compliance report document.

        Example return value:
            "outputs/compliance_report.md"
        """
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        md_content = "# CA6123 Pre-submission Compliance Checklist\n\n"
        
        # Architecture Statement: Clearly define the boundaries of responsibility between Member 3 and Member 4
        md_content += "> **ARCHITECTURE NOTICE**: The layout of this report is generated by the **Action Agent (Member 3)**. The actual compliance validation logic will be executed and injected by the **Compliance Agent (Member 4)** during the Learn/Evaluation phase.\n\n"
        
        # Region 1: List based on Reason stages
        md_content += "## 1. Action Items Checklist (Human Review)\n"
        for item in checklist_items:
            md_content += f"- [ ] {item}\n"
            
        # Region 2: Reserved output window for Member 4
        md_content += "\n## 2. Automated Compliance Score (Member 4 - Pending)\n"
        md_content += "> *This section is reserved for the ComplianceAgent.*\n"
        md_content += "- **Overall Target Score**: Pending...\n"
        md_content += "- **Missing Grading Criteria**: Pending...\n"
        md_content += "- **Safety / Responsible AI Status**: Pending Verification...\n"
            
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
            
        return output_path