import os
from typing import List

class ChecklistGenerator:
    """
    Tool suite for generating compliance and verification documents.
    """

    def generate_human_verification_checklist(self, checklist_items: List[str], output_path: str = "outputs/compliance_report.md") -> str:
        """
        Creates a pre-submission compliance checklist document in Markdown format to facilitate human review.
        Saves data directly to the local file system to minimize the LLM output context.

        Args:
            checklist_items: A list of string descriptions representing the required criteria to be checked.
            output_path: The file path destination for the generated checklist. Defaults to 'outputs/compliance_report.md'.

        Returns:
            A short string representing the file path to the generated compliance report document.

        Example return value:
            'outputs/compliance_report.md'
        """
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        md_content = "# ✅ CA6123 Pre-submission Compliance Checklist\n\n"
        md_content += "> **NOTICE**: This checklist is auto-generated by the Agent. Final submission MUST be reviewed and approved by **human team members**.\n\n"
        
        for item in checklist_items:
            md_content += f"- [ ] {item}\n"
            
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
            
        return output_path